### ISSUE TITLE
flow not recognised

### ISSUE THREAD

**Issue by SurajDonthi** [llSourcell/YOLO_Object_Detection#8]
Hey I got this error for running `flow --h`:
`'flow' is not recognized as an internal or external command,
operable program or batch file.`
Please let me know how to resolve this.

Thanks in advance.

**Comment by 3bu1** [comment]
@llSourcell being new to AI and yolo need little more explanation on how to use flow commands. As far as i understood i have to use them in python shell like python3 flow -h, right? can u elaborate how to use yolo..expecting couple of spoon feeds

**Comment by miranthajayatilake** [comment]
In windows `python flow --h` worked. 
But I got other errors with dependencies when trying other functions. So I cloned the original repo from https://github.com/thtrieu/darkflow/tree/d9fe7fc2bafbc5cb344a5335006a4d7edfda5c74. It works.

**Comment by SurajDonthi** [comment]
> In windows python flow --h worked.
> But I got other errors with dependencies when trying other functions. So I cloned the original repo from https://github.com/thtrieu/darkflow/tree/d9fe7fc2bafbc5cb344a5335006a4d7edfda5c74. It works.

Yes, I did the same and it works!

**Comment by thurussian** [comment]
ok, pls run us through exact steps to make darkflow work.  as detailed as you can from the beginning.  This will help me and many others.  Also I am guessing you used miniconda or anaconda to smooth the dependencies issues.
